first commit
rust2014/go_final_project pull request #1
Opened 2024-06-13 16:49 UTC by rust2014

Creation main.go and go.mod. Starting the web server.

2024-07-09 16:26 UTC, dirtymew requested changes
Привет Рустам

хорошая работа - отлично что добавил логирование

есть что поправить и отрефакторить 

также нужно дописать документацию указав как запустить приложение и тесты

задания со звездочкой будешь делать?

2024-07-09 16:26 UTC, dirtymew commented on .gitignore
> +.DS_Store
отлично что добавил но сами файлы есть в ветке их стоит убрать 
![Uploading image.png…]()

2024-07-09 16:26 UTC, dirtymew commented on main.go
> +	//database.ConnectDB()
лишние комменты убрать нужно

2024-07-09 16:26 UTC, dirtymew commented on handlers/handlers.go
> +	"github.com/rust2014/go_final_project/models"
что-то с имортами в проекте - используй goimports для группировки и сортировки импортов

2024-07-09 16:26 UTC, dirtymew commented on handlers/nextDate.go
> +func AddTask(db *sql.DB, task models.Task) (int64, error) { // создание новой задачи в бд
код очень странно разделен на файлы - стоит разнести и назвать файлы понятно

2024-07-09 16:26 UTC, dirtymew commented on handlers/handlers.go
> +func HandlerGetTasks(db *sql.DB) http.HandlerFunc { // обработчик для GET-запроса /api/tasks
очень перегружены хендлеры - выполняют много логики

это плохо с точки зрения разработки, поддержки и тд.

нужно выдели абстрации и отрефакторить код
пусть например хендлеры отвечают только за обработку запроса его валидацию и обработку ответа

остальную логику можно вынести в другие пакеты

вот мб помогу данные материалы
https://medium.com/@shershnev/layered-architecture-implementation-in-golang-6318a72c1e10
https://github.com/golang-standards/project-layout

2024-07-09 17:02 UTC, rust2014 commented
> Привет Рустам
> 
> хорошая работа - отлично что добавил логирование
> 
> есть что поправить и отрефакторить
> 
> также нужно дописать документацию указав как запустить приложение и тесты
> 
> задания со звездочкой будешь делать?

Привет! Благодарю за ревью. 
Задание со звездочкой хотел бы сделать, но сначала отправлю версию с доработоками.

2024-07-12 15:30 UTC, dirtymew requested changes
Привет Рустам

все в целом ок - можно еще немного улучшить 
дал комментарии

если хотел делать задания со * сейчас самое время - иначе после того как я приму задание уже на ревью не получиться отправить

2024-07-12 15:30 UTC, dirtymew commented on .gitignore
> +.DS_Store
все еще в ветке есть .DS_Store @rust2014

2024-07-12 15:30 UTC, dirtymew commented on services/services.go
> +	rows, err := db.Query("SELECT id, date, title, comment, repeat FROM scheduler ORDER BY date LIMIT 50")
лимит в константу лучше вынести

2024-07-12 15:30 UTC, dirtymew commented on services/services.go
> +func GetTask(db *sql.DB, id int) (*models.Task, error) {
чтобы постоянно не перекидывать конекшн к базе

лучше завести структуру которая будет хрванить его и все эти функции сделать ее методами

2024-07-12 15:30 UTC, dirtymew commented on services/services.go
> +	return result.RowsAffected()
а зачем result.RowsAffected() отдавать?  проверяй прямо тут и ошибку возвращай

так и интерфейс будет понятнее и ты логику не размазываешь по компонентам увеличивая связность

2024-07-12 15:30 UTC, dirtymew commented on services/dateUtils.go
> +func NextDateHandler(w http.ResponseWriter, r *http.Request) { // GET-обработчик api/nextdate
хендлеры все лучше в одном месте собрать - в handlers

2024-07-12 15:30 UTC, dirtymew commented on services/dateUtils.go
> +func NextDate(now time.Time, dateStr string, repeat string) (string, error) {
я бы отдельный пакет для работы с датами завел...

2024-07-12 15:30 UTC, dirtymew commented on services/dateUtils.go
> +const DefaultFormatDate = "20060102" // дефолтный формат
DefaultDateFormat

2024-07-14 15:08 UTC, rust2014 commented
Реализовал часть заданий со звездочкой, хочу сдать работу в таком виде.

2024-07-14 17:38 UTC, dirtymew approved these changes
Привет Рустам

задание считаю выполненным - есть вопросы по докеру но это уже задания со звездочкой


Поздравляю и желаю удачи

2024-07-14 17:38 UTC, dirtymew commented on services/addTaskService.go
> +func (s *TaskService) AddTask(task models.Task) (int64, error) { // создание новой задачи в бд
почему AddTask отдельно - лучше ко всем методам в service.go положить

2024-07-14 17:38 UTC, dirtymew commented on validation/jsonUtils.go
> +package validation
файл лучше проще назвать - json.go

2024-07-14 17:38 UTC, dirtymew commented on dates/dateUtils.go
> +package dates
dates/dateUtils.go ---> dates/dates.go

2024-07-14 17:38 UTC, dirtymew commented on compose.yaml
> +      - "7540:7540"
тут стоит TODO_PORT -тоже использовать

иначе при его изменении приложение будет слушать другой порт а докер прокинет 7540

2024-07-14 17:38 UTC, dirtymew commented on Dockerfile
> +RUN go mod tidy
лучше go mod download

2024-07-14 17:38 UTC, dirtymew commented on compose.yaml
> +    command: go run main.go
так не стоит делать лучше собрать в контейнере бинарник и его запускать (go build)

2025-02-05 15:06 UTC, merged